### ISSUE TITLE
All Files Are Empty....

### ISSUE THREAD

**Issue by Skarm-Ghelmaad** [don1138/blender-materials#1]
I've tried to open your blender materials in the latest blender, but, when I try to append them, they seem to be empty!!

**Comment by don1138** [comment]
Hm. I opened Blender 3.4 and appended from **Tutorials-2022-Q3.blend**, and they showed up fine. I also dragged and dropped from the Asset Browser and that also worked.

It might be possible that they aren't showing up in the Asset Browser even though they've successfully imported. You may just need to save and reload the file for them to show up.

Give it a try and let me know if you're still having problems.

**Comment by Skarm-Ghelmaad** [comment]
Ok...I will try!
Frankly I was assuming was a problem with them using the old Blender renderer...but if appending sees the file, I guess they shoul work... :-/ I will check to confirm...
